server.port=8080
spring.application.name=ewm-service

client.url=http://localhost:9090
app=ewm-main-service

spring.output.ansi.enabled=ALWAYS

# ????????? ??
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/ewm
spring.datasource.username=postgres
spring.datasource.password=postgres

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ??? ??????????
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# ??????????? (??? ???????)
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.engine.transaction=DEBUG
